### PR TITLE
File meta data in JSON

### PR DESCRIPTION
**Pull request by matejmoravec**
- Added parser for reading meta data from a simple JSON-based format
- A few unit tests for the newly added meta data parser have been added

This pull request addresses issue #210.

### CODE REVIEW

**Comment by matejmoravec** [comment]
Just one concern: I had to add a new value `INVALID` into the enum class [`ValueTypeCode`](https://github.com/matejmoravec/daphne/blob/210-file-meta-data/src/runtime/local/datastructures/ValueTypeCode.h). The script [build.sh,](https://github.com/daphne-eu/daphne/blob/main/build.sh) now shows many warnings everywhere where the enum class is used, usually because of not checking the newly added value. Maybe any recommendation on what to do here?

The next thing is that somewhere, "metadata" is used as one word and elsewhere as two words, "meta data." Maybe this should be unified in the future...

**Comment by matejmoravec** [comment]
> Just one concern: I had to add a new value `INVALID` into the enum class [`ValueTypeCode`](https://github.com/matejmoravec/daphne/blob/210-file-meta-data/src/runtime/local/datastructures/ValueTypeCode.h). The script [build.sh,](https://github.com/daphne-eu/daphne/blob/main/build.sh) now shows many warnings everywhere where the enum class is used, usually because of not checking the newly added value. Maybe any recommendation on what to do here?
> 
> The next thing is that somewhere, "metadata" is used as one word and elsewhere as two words, "meta data." Maybe this should be unified in the future...

The alternative solution is that I can set a default value from one of the existing (`SI8`, `SI32`, `SI64`, `UI8`, `UI32`, `UI64`, `F32`, or `F64`) in case the JSON format contains the unknown value for `ValueTypeCode`. In that case, I don't have to add a new value to the enum class.

**Comment by corepointer** [comment]
Hi!
I did not fully test this feature, but so far it LGTM. The change in terminology (metadata vs meta data) in comments can be easily addressed any time. The issue with warnings about the newly introduced INVALID enum can be fixed by either adding that to the switch statements that use ValueTypeCode or adding a default case. My compiler (gcc 11.2.0) found five occurrences where this is needed in CastObj.h, EwBinaryObjSca.h, ReadCsvFile.h, ReadDaphne.h and WriteDaphne.h. I silenced the warnings by putting this at the end of the switch statement: ```default: throw std::runtime_error("unknown value type code");```

**Comment by corepointer** [comment]
LGTM - Test suite runs fine. Merging with minor changes.

I found another warning of a switch statement in CheckEqApprox.h (noticable when running test.sh) and I beautified the inclusion of json.hpp ;-)

**Comment by matejmoravec** [comment]
> LGTM - Thank you for your contribution! 👍
> 
> #### Test suite runs fine. Merging with minor changes:
> * I found another warning of a switch statement in CheckEqApprox.h (noticable when running test.sh)
> * I beautified the inclusion of json.hpp ;-)

Great! Thank you.

**Pull request closed without merging**
