### PR TITLE
Draft: Distributed Runtime update

### LINKED ISSUE #96: Move distributed data structures and kernels to `src/runtime/distributed/`
In GitLab by @pdamme on Jul 30, 2021, 18:59

The distributed data structures (`Handle.h`) and kernels (`Distribute.h`, `DistributedCompute.h`, and `DistributedCollect.h`) currently reside in `src/runtime/local/`. However, they clearly belong to the distributed run-time. Thus, the directories `src/runtime/distributed/datastructures` and `src/runtime/distributed/kernels` should be created and those files moved there.

This necessitates changes to `genKernelInst.py` and `kernels.json`, since these currently assume local kernels. We could add a boolean flag `isDistributed` to all kernels in `kernels.json` (or `genKernelInst.py` could just check if the kernel header resides in `local` or `distributed`).

### PR DESCRIPTION
**Pull request by daphne-eu**
In GitLab by @aristotelis96 on Mar 29, 2022, 18:53

**Refactored distributed runtime**
These changes allow to fuse multiple operations and also enable vectorized execution at the distributed workers.
- Distributed runtime now works similar to the vectorized engine. Compiler fuses multiple operations into one to create a "distributed pipeline". Compiler provides the runtime with inputs and a mlir code fragment of the pipeline. Runtime is responsible for providing all the necessary inputs of the pipeline to the workers, along with the mlir code fragment. Finally collects from the workers and returns the result of the pipeline.
- Implemented `DistributedWrapper.h`. This kernel is responsible for executing a distributed pipeline (similar to `MTWrapper.h` for the vectorized engine).
- Updated folder structure. Moved all distributed-related code under `src/runtime/distributed/`

**Implemented `class DataPlacement`**

- Implemented `class DataPlacement`. `DataPlacement` is a field of `class Structure` and holds information regarding where data resides (cpu, worker, etc.).
- Removed `Handle` datatype. We no longer need this since all related information is located inside each `Structure` object.

**Support for various data types on the distributed runtime**

- Updated distributed runtime to support `DenseMatrix<int64_t>` and `CSRMatrix<double/int64_t>`. Distributed runtime only supported operations with `DenseMatrix<double>`, it now supports other datatypes. 
- For now only `DenseMatrix<double>` is supported for result of the distributed pipeline, however the operands can be other types.

**Serialization**

- Created pure `virtual convertToProto()` and `convertFromProto` functions for `class Structure`. Each object can now be serialized to `protobuf`s by using this method.
- Removed `static class ProtoDataConverter`

This closes #96 #194

### CODE REVIEW

**Review by corepointer — CHANGES_REQUESTED** [review]
I see the great effort and big improvement with this PR @aristotelis96!
But you introduce a direct dependency on grpc in the data structures that could be isolated better with an abstract interface. This would make exchanging grpc in the future an easier task and also facilitate merging with PR #334 
What would be required for that is to rebase once that PR is merged and implement the IAllocationDescriptor interface via DataPlacement and move all grpc specifics into that class. We can adapt that abstract interface to your needs of course.
Regards, Mark

**Comment by aristotelis96** [comment]
Thank you @corepointer for your great suggestions! For now I've marked this PR as Draft. I'll start working based on work from PR #334 and we can merge this, once #334 is merged.

**Comment by corepointer** [comment]
Great! Reach out to me if you have any questions.

**Comment by aristotelis96** [comment]
After discussing here and on issue #367, I am closing this PR. Further progress on the distributed runtime can be found at PR #428.

**Pull request closed without merging**
