### PR TITLE
Build script improvements

### PR DESCRIPTION
**Pull request by corepointer**
This PR contains several minor and major improvements to our infamous build script. Some of it is prep work for building daphne containers.

Commit messages speak for themselves but here's a quick summary:

* The clean parameters are changed according to #466 
* The prefix where third party dependencies are installed can be set with --installPrefix <path>
* The LLVM/MLIR dependency is now installed into installPrefix and the use of buildPrefix removed from the main cmake config invocation (at the bottom of build.sh)
* Third party dependency compilation can be omitted via --no-deps flag

### CODE REVIEW

**Comment by auge** [comment]
Hi,
where do you have the image `daphneeu/github-action:latest` available?
* is the source on github (account daphne-eu) ?
* is the image on docker hub ?

**Comment by corepointer** [comment]
> Hi, where do you have the image `daphneeu/github-action:latest` available?
> 
>     * is the source on github (account daphne-eu) ?
> 
>     * is the image on docker hub ?

I set up the daphneeu account on Docker Hub (no "-" allowed, otherwise it would have been daphne-eu there too). We'll change that account to an organization. 

The image can be pulled from Docker Hub. This was a first test. I'll push some more images soon and add the source to our Github repo as well.

**Review by pdamme — CHANGES_REQUESTED** [review]
Hi @corepointer, thanks for these useful improvements of the build script and documentation. **Overall, it looks good to me**, however, here are a few comments, some of which should be addressed:

**Required, IMHO:**
- The top-level `CMakeLists.txt` still hardcodes the default third-party installation prefix for arrow (optional dependency), so setting `--installPrefix` won't have an effect here.
- `GettingStarted.md` says that DAPHNE can be built on all Ubuntu versions in the range 20.04 to 22.10. However, on my Ubuntu 22.04 system, it does not work out of the box. Have you tried it with 22.04? I can provide more details if needed, but we don't need to make it work right now, but should document it accurately.
- Minor: Please consistenly use an indentation of 4 spaces in `build.sh`.

**Optional:**
- While it is not strictly an error, I noticed a somewhat unintuitive behavior. Assume we have a fully built repo (DAPHNE and dependencies), using the default install prefix. Now, invoking `./build.sh --installPrefix "$(pwd)/thirdparty/my_installed"` has no effect. Since all the install success token files are present, nothing is built anew and nothing will be in the new install prefix `$(pwd)/thirdparty/my_installed`. So we need to do `./build.sh --cleanDeps` first to get rid of the old built/installed third-party deps. Now, invoking `./build.sh --installPrefix "$(pwd)/thirdparty/my_installed"` causes a rebuild of the third-party deps, but many of the variables/paths in cmake were *cached* so they still point to the old/default install prefix. This even causes the build to fail (for antlr in my case, but I think the problem is more general). 
  ```
  -- CMAKE_PREFIX_PATH:  /daphne/thirdparty/my_installed
  -- ANTLR_JAR_FOUND: /daphne/thirdparty/my_installed/share/antlr4/antlr-4.9.2-complete.jar
  -- ANTLR4_JAR_LOCATION is /daphne/thirdparty/installed/share/antlr4/antlr-4.9.2-complete.jar
  CMake Error at thirdparty/my_installed/lib/cmake/antlr4-generator/antlr4-generator-config.cmake:156 (message):
    Unable to find antlr tool.
    ANTLR4_JAR_LOCATION:/daphne/thirdparty/installed/share/antlr4/antlr-4.9.2-complete.jar
  ```
  So we need to do `./build.sh --clean` as well to get rid of the cached variables. That may all be fine, since one may not change the install prefix very often. But at least we should document that, i.e., before invoking `build.sh` with another install prefix, one should at least do `./build.sh --clean && ./build.sh --cleanDeps`.
- MLIR: You also build the target `install`. We had discussed this a while ago in #359. It adds more targets to build (~700), which takes some more time. You provided a clear justification in the commit message, and I'm fine with it if it simplifies things. I'm just wondering why it helps, because we never used any of the outputs of the install target before.

**I have also pushed a few minor fixes** to your branch. Feel free to handle them as you wish (e.g., integrate into your existing commits).

**Comment by corepointer** [comment]
Thx for your comments @pdamme 
* The Arrow paths hard coded in CMakeLists.txt might explain troubles I had with adding that to the Docker image. I'll have a closer look at it. I was actually considering removing the --arrow flag and just compiling it anyway. I'll open a separate issue reasoning about it.
* Yes I had DAPHNE running at times when Ubuntu 22.04 was the current version. But I didn't test it recently. If you share more details about your troubles in another issue we'll figure it out.
* I had in the back of my head that we use 2 spaces for indentation in scripts. I'll let my formatter have a go at it ;-)
* Yes, the cached paths are a problem. I think documenting that caches need to be cleared if the installPrefix is changed is a solution we can live with (to not over engineer the already quite elaborate(to use another wording ;-)) build script).
*  Imho we use quite a lot of the LLVM and MLIR libraries, binaries and include files in DAPHNE. Removing the reference to buildPrefix tremendously reduces the size of the Docker image with prebuilt deps (saving 6GB). As I mentioned somewhere, many of the changes are related to better handling of the Docker images and also the github action. So having those extra 700 compile steps in the dependency compilation should pay of as people won't have to compile dependencies over and over again if they either use the containers or have the dependencies compiled once into a directory that can be moved out of the way when cleaning the source tree.

**Review by pdamme — CHANGES_REQUESTED** [review]
Hi @corepointer, thanks for the fixes and additions. Quickly glancing over it, it looks good to me. There do not seem to be so many changes to the commits that existed before you incorporated my feedback (except for some docu). The two latest commits on reformatting `build.sh` and on improving the Arrow integration were added.

I pushed a minor fix removing `USE_ARROW` from the `ReadParquet` test case.

For testing, I did the following:
- clone freshly and `./build.sh` and `./test.sh`: success
- `./build.sh --clean` and `./build.sh`: success
- `./build.sh --cleanDeps`: success (and expected files removed)
- `./build.sh --cleanCache`: no prompt, but some error and then the script continues doing unrelated things...
  ```
  root@3c7b6b5a37fa:/daphne# ./build.sh --cleanCache
  -- Cleanup of downloaded/extracted artifacts of the third party dependencies
  ./build.sh: line 225: `/daphne/thirdparty/sources': not a valid identifier
  [DAPHNE]..Applying 0000-antlr-silence-compiler-warnings.patch.............................................................................................................................[10.02.23 20:27:56]
  patching file runtime/src/atn/ATNState.h
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored -- saving rejects to file runtime/src/atn/ATNState.h.rej
  patching file runtime/src/support/Any.h
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored -- saving rejects to file runtime/src/support/Any.h.rej
  [DAPHNE]..Build Antlr v4.9.2..............................................................................................................................................................[10.02.23 20:27:56]
  [...]
  ```

**Please double check what's going wrong here.**

**Review by pdamme — APPROVED** [review]

**Review by pdamme — CHANGES_REQUESTED** [review]
Sorry, approved by accident, but there are still problems to fix.

**Comment by pdamme** [comment]
Anyway, the required points from my first review have been fixes (we can talk about Ubuntu 22.04 later), and the optional points are also fine (Arrow, and I see the point about the MLIR install target and agree with you).

**Pull request merged**
