### PR TITLE
Draft: [DAPHNE-#118] Documentation of DaphneDSL

### LINKED ISSUE #118: Basic user documentation for DaphneDSL
In GitLab by @pdamme on Sep 14, 2021, 21:51

This documentation of the current state of DaphneDSL should allow users to quickly learn the basics of DaphneDSL, such that they can write their own scripts. For this purpose, the documentation should touch at least the following topics:

- types and variables
- expressions
- statements (assignments, control structures, ...)
- variable scoping
- list of built-in functions

Inspiration can be takes from various other languages (e.g. from [SystemDS's DML](https://apache.github.io/systemds/site/dml-language-reference)).

Since DaphneDSL is still evolving, the document could also provide a few pointers into the source code for the most up-to-date state.

### PR DESCRIPTION
**Pull request by daphne-eu**
In GitLab by @pdamme on Mar 18, 2022, 21:05

On this branch/MR, we're writing an initial documentation of DaphneDSL.

Closes #118 (once it's ready).

### CODE REVIEW

**Comment by RetoKrummenacher** [comment]
@pdamme 
Are the missing parts of the documentation (Statements, Functions, File I/O) added soon?

**Comment by pdamme** [comment]
Hi @RetoKrummenacher, continuing with this documentation is definitely on my todo list and I'll try to push this further now. Unfortunately, I cannot promise to finish it in the next few days...

In the meantime, I recommend having a look at the script-level test cases in `test/api/cli/`, which contain examples of almost all DaphneDSL language features that are already working. For instance, all kinds of statements can be found in `test/api/cli/controlflow/*.daphne`, user-defined functions can be found in `test/api/cli/functions/*.daphne`. A list of built-in functions can be found in `src/parser/daphnedsl/DaphneDSLBuiltins.cpp`, for the time being. In addition to those, there are some examples of small algorithms in `test/api/cli/algorithms/` and `scripts/`.

And of course, if you have any specific questions, don't hesitate to ask them directly.

**Comment by pdamme** [comment]
I will close this PR and reopen it in my own name (it was opened before the migration from GitLab).

**Comment by pdamme** [comment]
Respectively, I will push it directly to main ;) .

**Pull request closed without merging**
