### PR TITLE
Introduce .clang-format file

### PR DESCRIPTION
**Pull request by philipportner**
This PR aims to introduce a `.clang-format` file in order to have automated consistent code formatting for supported languages. For DAPHNE this mainly aims to do so for C, C++ and TableGen files.
`clang-format` is the standard tool to provide consistent formatting across C and C++ code bases and is supported by almost every editor and IDE out there (e.g., automatically recognized by Clion/VScode). 

It even has [integration](https://clang.llvm.org/docs/ClangFormat.html#git-integration) with `git` itself.

The following steps would need to be completed:

- [x] Decide on format
- [x] Run `clang-format` on whole project
- [x] Push these changes with a systems account
- [x] optional - Handle blame annotation for project

I don't really care which format we use, main thing is consistency. I added the `LLVM` style for now since that makes the most sense for me with our dependency on LLVM.

Happy to discuss specifics and feel free to ask any questions and please let me know if there's more steps needed.

https://clang.llvm.org/docs/ClangFormat.html

### CODE REVIEW

**Comment by corepointer** [comment]
Thx for initiating discussion on coding style :+1: We've been avoiding it for far too long ;-) :see_no_evil:

**Comment by philipportner** [comment]
To ignore whitespace changes with `git blame` one has to pass the `-w` option as argument, e.g., `git blame -w path_to_file`.

https://www.git-scm.com/docs/git-blame

**Comment by pdamme** [comment]
This PR is related to #70 and perhaps to #16.

**Comment by corepointer** [comment]
In the future, please add a reference to the GitHub discussion to the commit message before merging to main. Something like "[DAPHNE-#723] Introduce .clang-format file"

**Comment by corepointer** [comment]
And maybe we could have a mention in the contribution guidelines on how to use it :nerd_face:

**Comment by philipportner** [comment]
> And maybe we could have a mention in the contribution guidelines on how to use it 🤓

Yes, I'll do that. Thanks

**Pull request merged**
