### PR TITLE
Distributed runtime documentation.

### PR DESCRIPTION
**Pull request by aristotelis96**
Added two .md files, both related to the use and development of the distributed runtime.
- One documentation file for the Daphne user, how to deploy distributed nodes (workers) and execute a script on the distributed runtime.
- One documentation file for the Daphne developer, explaining the basics on how to extend the existing infrastructure of the distributed runtime.

### CODE REVIEW

**Comment by pdamme** [comment]
Thanks @aristotelis96, any documentation is highly welcome! I will give it a read by Tue.

**Comment by aleszamuda** [comment]
Hi, I have updated the issue #437 description in order to explain how documentation for `deploy/` could help addressing the points 1-4 in @pdamme comment https://github.com/daphne-eu/daphne/pull/431#pullrequestreview-1136148570.

**Comment by aristotelis96** [comment]
Thanks @pdamme for reviewing this PR. You are right `--target DistributedWorker` should be mentioned when building the worker, this is now fixed. Regarding your comments:
1. Added. I've also added a "Limitations" section specifing that workers might end up using all their memory, when used for multiple scripts.
2. I agree, this sounds good. Added.
4. @aleszamuda is working on this. After this is completed we can reference a ".md" file here, instead of a directory.
5. Added.
6. Added. @AhmedEleliemy is currently working on MPI support (PR #436). This PR also includes implementation of a new cli argument that enables the user to select a specifing distributed backend. Once #436 is merged this section will be updated.

**Comment by pdamme** [comment]
Thanks @aristotelis96 for the updates. Looks good to me.

I think we could mention more limitations (also to clarify that DAPHNE's distribution capabilities are not fully developed yet), e.g.:
- focus on `DenseMatrix` as the data type (no sparse matrices, no frames)
- focus on `f64` as the value type (no various other value types)

Regarding my initial point 3: Would it be possible to run one of the scripts in `scripts/algorithms/` on the distributed runtime?

**Comment by aristotelis96** [comment]
Thank you for your comments @pdamme. Please note that I've rebased and force-pushed. Adding these limitations is very important. I've also added a few more:

- Distributed runtime and vectorized engine do not support  pipelines with no outputs.
- Distributed runtime and vectorized engine do not support results with individual result types #397.
-  Distributed runtime does not support duplicate pipeline inputs. 

Regarding `scripts/algorithms`, unfortunately none of them can be run on the distributed runtime at the moment. Actually, distributed runtime depends on the vectorized engine (for pipeline creation) and I could not execute any of these scripts with the `--vec` flag:

- components: operand # 4 does not dominate this use (also duplicate pipeline-input error for the distributed runtime)
- gnmf: vectorizedPipelineOp without outputs not supported at the moment!
- lmDS: error: operand # 4 does not dominate this use
- multilogRef: vectorizedPipelineOp without outputs not supported at the moment!
- pca: "tableOp" is missing (however ctable is implemented (#390), are `ctable` and `table` the same?)

**Comment by pdamme** [comment]
Thanks, looks good to me.

I wasn't aware that there are still those problems with the scripts. I thought we had fixed them for all but 1 or 2 scripts... If I find the time, I'll have a look at them.

Regarding the limitations, it's right to mention them, but maybe we should call them "Current Limitations" and clarify that we are going to fix them at some point.

**Comment by aristotelis96** [comment]
Thank you @pdamme. I've renamed the section to "Current limitations" and noted that these will be fixed in the future. 
I've also rebased to main branch.

**Review by pdamme — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
