### PR TITLE
Documentation of scheduling options and extensions

### PR DESCRIPTION
**Pull request by AhmedEleliemy**
This pull request includes documentation about the use of scheduling options in daphne. Also, I have moved the documentation about how to extend DAPHNE by adding a new partition scheme into the doc/development folder

### CODE REVIEW

**Comment by AhmedEleliemy** [comment]
@corepointer @aristotelis96 could you have a look and provide your feedback?

**Comment by aristotelis96** [comment]
Thanks @AhmedEleliemy for this pull request. It looks very good to me. A few minor comments:

Regarding `SchedulingOptions.md`:
- Deliverable 5.1 is mentioned in the document (and 4.1 in the references), it would be nice to provide hyperlinks to these documents.
- You are providing the `daphne --help` output and you mention that you include _only the scheduling options that we will cover in this deliverable_. Instead of _deliverable_ we should probably use another word here (documentation?) and also some of the output could be omitted (`--explain`, `--cuda`, `--help`, etc.).

Regarding `ExtengingSchedulingKnobs.md`:
- There are several mentions to the Daphne "end-user" (or simply "user"), however IMHO "Daphne developer" could be more appropriate in this document.

**Comment by AhmedEleliemy** [comment]
@aristotelis96  thanks for your feedback.  I just kept the output of the help command even though it contains options that are not scheduling options. I did not want to confuse the reader, i.e., if users executed the help, they will get the same output.  But, thanks for the feedback I implemented it :)

**Comment by pdamme** [comment]
Thanks for providing feedback @aristotelis96. Feel free to handle this PR until the merge (see the developer docs for some guidelines on handling PRs). Let us know if you need any help :) .

**Comment by aristotelis96** [comment]
@pdamme I'll be happy to handle and merge this PR.

**Review by aristotelis96 — APPROVED** [review]

**Pull request merged**
