### PR TITLE
Implementation of CSR/CSR Matrix Multiplication (`@`)

### PR DESCRIPTION
**Pull request by GuilloteauQ**
This PR implements a kernel for the matrix multiplication between two CSR matrices.

Related Issue: #793 

Fixes also #783 

## Questions

- I needed to provide an estimation of the number of non-zeros elements for the resulting matrix. I had a "guess" but probably this guess can be improved (maybe: https://link.springer.com/content/pdf/10.1023/A:1009716300509.pdf)
- I am not sure if I need to add more to the `kernels.json`? like for other types than `double`

### CODE REVIEW

**Comment by corepointer** [comment]
Sparsity estimation is being worked on in #790. Maybe the link you provided here can be of help there? @Garic152

**Comment by corepointer** [comment]
Some test cases would be awesome. Maybe something similar to the dense mat mult test?

**Comment by Garic152** [comment]
> Sparsity estimation is being worked on in #790. Maybe the link you provided here can be of help there?

Thanks, I'll definetly take a look at it!

**Comment by corepointer** [comment]
Thx for submitting this PR @GuilloteauQ. I merged with some cleanup and test cases and added a commit that circumvents the missing transposition functionality. Since you implemented this already as mentioned in #793 I'd kindly ask you to provide this implementation as well. Ideally you can also modify the compiler logic to use the method with or w/o the transposition depending on the situation.

**Pull request merged**
